FROM golang:alpine

ARG GITHUB_BRANCH

RUN apk update && apk add git
RUN go get -u github.com/FiloSottile/gvt

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/pulse-eight-neo-microservice

WORKDIR /go/src/github.com/byuoitav/pulse-eight-neo-microservice
RUN gvt fetch -branch ${GITHUB_BRANCH} github.com/byuoitav/configuration-database-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/pulse-eight-neo-microservice"]

EXPOSE 8011
