FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install ca-certificates

RUN mkdir -p /go
ADD . /go

WORKDIR /go

CMD ["/go/pulse-eight-neo-microservice"]

EXPOSE 8011

RUN [ "cross-build-end" ]
